"""The alembic chain and ``Base.metadata`` must describe the same tables.

The rest of the suite builds its schema with ``Base.metadata.create_all``
and never replays the migrations, so a table that the chain creates but
no model backs is invisible to every other test. ``heartbeat_items`` sat
in that blind spot from #662 (which deleted the ``HeartbeatItem`` model
without dropping the table) until revision 040, and the symptom was that
``alembic revision --autogenerate`` emitted ``drop_table('heartbeat_items')``
into every new migration.

These tests replay the real chain against a scratch database and compare
the result to ``Base.metadata``, so the next orphan fails here instead of
turning up inside someone's unrelated autogenerated migration.
"""

from __future__ import annotations

import os
import subprocess
import sys
from collections.abc import Generator
from pathlib import Path

import psycopg
import pytest
from psycopg import sql

import backend.app.models  # noqa: F401 -- registers every table on Base.metadata
from backend.app.database import Base

_REPO_ROOT = Path(__file__).resolve().parent.parent
_PG_ADMIN_URL = "postgresql://clawbolt:clawbolt@localhost:5432/postgres"

# Alembic's own bookkeeping table has no model by design.
_UNMANAGED_TABLES = {"alembic_version"}


def _scratch_db_name() -> str:
    """Dedicated database per branch / xdist worker.

    The chain has to run against an empty database, and it leaves the
    schema at head rather than at whatever the rest of the suite
    expects, so it cannot share ``clawbolt_test``.

    Resolution order mirrors ``_resolve_test_db_name`` in ``conftest.py``
    so that ``OSS_TEST_DB``, the documented escape hatch for several
    agents or branches running pytest at once, isolates this database
    too. Without it, two concurrent runs race on CREATE DATABASE and the
    loser's teardown force-drops the winner's scratch DB mid-chain.
    """
    explicit = os.environ.get("OSS_TEST_DB")
    if explicit:
        return f"{explicit}_migrchain"
    worker = os.environ.get("PYTEST_XDIST_WORKER", "main")
    return f"clawbolt_migrchain_{worker}"


@pytest.fixture(scope="module")
def scratch_db_url() -> Generator[str]:
    """Create an empty database, yield its sync URL, drop it after."""
    name = _scratch_db_name()
    with psycopg.connect(_PG_ADMIN_URL, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)").format(sql.Identifier(name)))
        cur.execute(sql.SQL("CREATE DATABASE {} OWNER clawbolt").format(sql.Identifier(name)))

    yield f"postgresql://clawbolt:clawbolt@localhost:5432/{name}"

    with psycopg.connect(_PG_ADMIN_URL, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)").format(sql.Identifier(name)))


def _alembic(scratch_db_url: str, *args: str) -> None:
    """Run alembic against the scratch DB the way deploy does.

    A subprocess rather than ``alembic.command`` so the ``DATABASE_URL``
    the chain reads is the one this test sets, without reaching into the
    process-wide cached ``settings`` object.
    """
    env = {**os.environ, "DATABASE_URL": scratch_db_url}
    env.setdefault("ENCRYPTION_KEY", "dGVzdC1lbmNyeXB0aW9uLWtleS0zMi1ieXRlcy1sb25nIQ==")
    result = subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=_REPO_ROOT,
        env=env,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, f"alembic {' '.join(args)} failed:\n{result.stderr}"


def _table_names(scratch_db_url: str) -> set[str]:
    with psycopg.connect(scratch_db_url) as conn, conn.cursor() as cur:
        cur.execute("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
        return {row[0] for row in cur.fetchall()}


@pytest.fixture(scope="module")
def migrated_tables(scratch_db_url: str) -> set[str]:
    """Table names after replaying the whole chain to head."""
    _alembic(scratch_db_url, "upgrade", "head")
    return _table_names(scratch_db_url)


def test_chain_creates_no_table_without_a_model(migrated_tables: set[str]) -> None:
    """Every table the chain builds is backed by ``Base.metadata``.

    An orphan here is what makes ``--autogenerate`` emit a spurious
    ``drop_table`` that the next person has to notice and delete.
    """
    orphans = migrated_tables - set(Base.metadata.tables) - _UNMANAGED_TABLES
    assert not orphans, (
        f"tables created by the alembic chain with no backing model: {sorted(orphans)}. "
        "Either add the model or write a migration dropping the table."
    )


def test_chain_creates_every_table_the_models_declare(migrated_tables: set[str]) -> None:
    """The converse: no model whose table the chain forgot to create."""
    missing = set(Base.metadata.tables) - migrated_tables
    assert not missing, (
        f"models declare tables the alembic chain never creates: {sorted(missing)}. "
        "A fresh deploy would start without them."
    )


def test_heartbeat_items_is_gone(migrated_tables: set[str]) -> None:
    """Regression anchor for the orphan revision 040 removed."""
    assert "heartbeat_items" not in migrated_tables


def test_040_downgrade_restores_heartbeat_items(
    scratch_db_url: str, migrated_tables: set[str]
) -> None:
    """040 is reversible, so a rollback past it does not strand the DB.

    Runs last in the module and restores head afterwards so the shared
    ``migrated_tables`` state stays true for reruns.
    """
    _alembic(scratch_db_url, "downgrade", "039")
    try:
        assert "heartbeat_items" in _table_names(scratch_db_url)
    finally:
        _alembic(scratch_db_url, "upgrade", "head")


def test_040_upgrades_cleanly_when_table_is_already_absent(
    scratch_db_url: str, migrated_tables: set[str]
) -> None:
    """A database that never had ``heartbeat_items`` still upgrades.

    Databases bootstrapped by ``create_all`` after #662 never got the
    table, because no model declares it. 040 drops it conditionally so
    those deploys do not fail on a missing table.
    """
    _alembic(scratch_db_url, "downgrade", "039")
    try:
        with psycopg.connect(scratch_db_url, autocommit=True) as conn, conn.cursor() as cur:
            cur.execute("DROP TABLE heartbeat_items")
        _alembic(scratch_db_url, "upgrade", "head")
        assert "heartbeat_items" not in _table_names(scratch_db_url)
    finally:
        _alembic(scratch_db_url, "upgrade", "head")
