"""The alembic chain and ``Base.metadata`` must describe the same tables.

The rest of the suite builds its schema with ``Base.metadata.create_all``
and never replays the migrations, so a table that the chain creates but
no model backs is invisible to every other test. ``heartbeat_items`` sat
in that blind spot from #662 (which deleted the ``HeartbeatItem`` model
without dropping the table) until revision 040, and the symptom was that
``alembic revision --autogenerate`` emitted ``drop_table('heartbeat_items')``
into every new migration.

These tests replay the real chain against a scratch database and compare
the result to ``Base.metadata``, so the next orphan fails here instead of
turning up inside someone's unrelated autogenerated migration.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from collections.abc import Generator
from pathlib import Path

import psycopg
import pytest
from psycopg import sql

import backend.app.models  # noqa: F401 -- registers every table on Base.metadata
from backend.app.database import Base

_REPO_ROOT = Path(__file__).resolve().parent.parent
_PG_ADMIN_URL = "postgresql://clawbolt:clawbolt@localhost:5432/postgres"

# Alembic's own bookkeeping table has no model by design.
_UNMANAGED_TABLES = {"alembic_version"}

# The eight tables revision 041 adopted from the retired premium chain.
# Asserted explicitly rather than left to the generic comparison so a
# migration that silently stops creating one of them fails here.
_ADOPTED_TABLES = {
    "admin_api_keys",
    "admin_audit_logs",
    "allowed_emails",
    "deleted_user_usage",
    "llm_payload_captures",
    "subscriptions",
    "usage_quotas",
    "waitlist_entries",
}

# The two ``users`` columns revision 041 adopts alongside those tables.
_ADOPTED_USER_COLUMNS = {"last_login_at", "inactivity_warned_at"}


def _scratch_db_name() -> str:
    """Dedicated database per branch / xdist worker.

    The chain has to run against an empty database, and it leaves the
    schema at head rather than at whatever the rest of the suite
    expects, so it cannot share ``clawbolt_test``.

    Resolution order mirrors ``_resolve_test_db_name`` in ``conftest.py``
    so that ``OSS_TEST_DB``, the documented escape hatch for several
    agents or branches running pytest at once, isolates this database
    too. Without it, two concurrent runs race on CREATE DATABASE and the
    loser's teardown force-drops the winner's scratch DB mid-chain.
    """
    explicit = os.environ.get("OSS_TEST_DB")
    if explicit:
        return f"{explicit}_migrchain"
    worker = os.environ.get("PYTEST_XDIST_WORKER", "main")
    return f"clawbolt_migrchain_{worker}"


@pytest.fixture(scope="module")
def scratch_db_url() -> Generator[str]:
    """Create an empty database, yield its sync URL, drop it after."""
    name = _scratch_db_name()
    with psycopg.connect(_PG_ADMIN_URL, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)").format(sql.Identifier(name)))
        cur.execute(sql.SQL("CREATE DATABASE {} OWNER clawbolt").format(sql.Identifier(name)))

    yield f"postgresql://clawbolt:clawbolt@localhost:5432/{name}"

    with psycopg.connect(_PG_ADMIN_URL, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)").format(sql.Identifier(name)))


def _alembic(scratch_db_url: str, *args: str) -> None:
    """Run alembic against the scratch DB the way deploy does.

    A subprocess rather than ``alembic.command`` so the ``DATABASE_URL``
    the chain reads is the one this test sets, without reaching into the
    process-wide cached ``settings`` object.
    """
    env = {**os.environ, "DATABASE_URL": scratch_db_url}
    env.setdefault("ENCRYPTION_KEY", "dGVzdC1lbmNyeXB0aW9uLWtleS0zMi1ieXRlcy1sb25nIQ==")
    result = subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=_REPO_ROOT,
        env=env,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, f"alembic {' '.join(args)} failed:\n{result.stderr}"


def _table_names(scratch_db_url: str) -> set[str]:
    with psycopg.connect(scratch_db_url) as conn, conn.cursor() as cur:
        cur.execute("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
        return {row[0] for row in cur.fetchall()}


def _column_names(scratch_db_url: str, table: str) -> set[str]:
    with psycopg.connect(scratch_db_url) as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = %s",
            (table,),
        )
        return {row[0] for row in cur.fetchall()}


@pytest.fixture(scope="module")
def migrated_tables(scratch_db_url: str) -> set[str]:
    """Table names after replaying the whole chain to head."""
    _alembic(scratch_db_url, "upgrade", "head")
    return _table_names(scratch_db_url)


def test_chain_creates_no_table_without_a_model(migrated_tables: set[str]) -> None:
    """Every table the chain creates has a backing model.

    An orphan here is what makes ``--autogenerate`` emit a spurious
    ``drop_table`` that the next person has to notice and delete.
    """
    orphans = migrated_tables - set(Base.metadata.tables) - _UNMANAGED_TABLES
    assert not orphans, (
        f"the alembic chain creates tables no model declares: {sorted(orphans)}.\n"
        "Add the model, or write a migration dropping the table."
    )


def test_chain_creates_every_table_the_models_declare(migrated_tables: set[str]) -> None:
    """The converse: no model whose table the chain forgot to create."""
    missing = set(Base.metadata.tables) - migrated_tables
    assert not missing, (
        f"models declare tables the alembic chain never creates: {sorted(missing)}. "
        "A fresh deploy would start without them."
    )


def test_heartbeat_items_is_gone(migrated_tables: set[str]) -> None:
    """Regression anchor for the orphan revision 040 removed."""
    assert "heartbeat_items" not in migrated_tables


def test_040_downgrade_restores_heartbeat_items(
    scratch_db_url: str, migrated_tables: set[str]
) -> None:
    """040 is reversible, so a rollback past it does not strand the DB.

    Restores head afterwards so the database the module-scoped
    ``migrated_tables`` describes stays at head for the tests after this
    one.
    """
    _alembic(scratch_db_url, "downgrade", "039")
    try:
        assert "heartbeat_items" in _table_names(scratch_db_url)
    finally:
        _alembic(scratch_db_url, "upgrade", "head")


def test_040_upgrades_cleanly_when_table_is_already_absent(
    scratch_db_url: str, migrated_tables: set[str]
) -> None:
    """A database that never had ``heartbeat_items`` still upgrades.

    A database built by ``create_all`` against current models never gets
    the table, because no model declares it. Deploys replay the chain
    instead and so always have it, which makes 040's conditional drop
    defensive rather than load-bearing. This locks that behavior in.
    """
    _alembic(scratch_db_url, "downgrade", "039")
    try:
        with psycopg.connect(scratch_db_url, autocommit=True) as conn, conn.cursor() as cur:
            cur.execute("DROP TABLE heartbeat_items")
        _alembic(scratch_db_url, "upgrade", "head")
        assert "heartbeat_items" not in _table_names(scratch_db_url)
    finally:
        _alembic(scratch_db_url, "upgrade", "head")


def test_041_adopts_the_premium_schema(scratch_db_url: str, migrated_tables: set[str]) -> None:
    """The premium tables and ``users`` columns are in the OSS chain.

    Before revision 041 these were built by the separate
    ``alembic_version_premium`` chain, so a fresh OSS database did not
    have them.
    """
    assert migrated_tables >= _ADOPTED_TABLES
    assert _column_names(scratch_db_url, "users") >= _ADOPTED_USER_COLUMNS


def test_041_downgrade_removes_the_premium_schema(
    scratch_db_url: str, migrated_tables: set[str]
) -> None:
    """041 is reversible, so a rollback past it does not strand the DB."""
    _alembic(scratch_db_url, "downgrade", "040")
    try:
        assert not (_ADOPTED_TABLES & _table_names(scratch_db_url))
        assert not (_ADOPTED_USER_COLUMNS & _column_names(scratch_db_url, "users"))
    finally:
        _alembic(scratch_db_url, "upgrade", "head")


def test_autogenerate_emits_no_destructive_operations(
    scratch_db_url: str, migrated_tables: set[str], tmp_path: Path
) -> None:
    """Autogenerate must not propose dropping anything at head.

    A drop here means the models and the chain have drifted: something
    the chain creates is no longer declared, and the next person to run
    ``--autogenerate`` gets that drop handed to them inside an otherwise
    unrelated migration. Runs the real CLI against the real ``env.py``,
    which cannot be imported because it runs migrations at import time.

    Writes into a copy of ``alembic/versions`` so the repository is never
    touched by a generated file.
    """
    versions = tmp_path / "versions"
    versions.mkdir()
    for migration in (_REPO_ROOT / "alembic" / "versions").glob("*.py"):
        shutil.copy(migration, versions)

    # ``%(here)s`` resolves against the ini's own directory, so the copied
    # ini needs absolute paths back to the real script_location.
    ini_lines = [
        f"script_location = {_REPO_ROOT / 'alembic'}\nversion_locations = {versions}"
        if line.startswith("script_location")
        else line
        for line in (_REPO_ROOT / "alembic.ini").read_text().splitlines()
    ]
    ini = tmp_path / "alembic.ini"
    ini.write_text("\n".join(ini_lines))

    _alembic(scratch_db_url, "-c", str(ini), "revision", "--autogenerate", "-m", "probe")

    generated = [p for p in versions.glob("*.py") if p.name.endswith("_probe.py")]
    assert len(generated) == 1, f"expected one generated migration, got {generated}"
    # Only the upgrade half. The downgrade of any legitimate ``create_table``
    # is a ``drop_table``, so scanning the whole file would fail on unrelated
    # model-vs-chain drift and blame the ``include_object`` filter for it.
    upgrade_body = generated[0].read_text().split("def downgrade(")[0]
    drops = [line.strip() for line in upgrade_body.splitlines() if "op.drop" in line]
    assert not drops, (
        "autogenerate emitted destructive operations against objects the chain "
        "creates but no model declares:\n  " + "\n  ".join(drops)
    )
