"""KMS-backed envelope-encryption KEK provider.

Implements the OSS ``KEKProvider`` Protocol using AWS KMS for DEK
wrapping. Each per-row DEK generated by ``EncryptedString`` is sent to
KMS Encrypt; the returned ciphertext blob is what we store inline in
the envelope. On read, the wrapped blob goes back through KMS Decrypt.

Falls through to a ``LocalKEKProvider`` for legacy ``kek_id="local"``
rows that predate the KMS rollout. Without that fallback, the moment
KMS is enabled in prod every existing token would become unreadable.
A re-key migration eventually moves all rows to ``kek_id="kms"``;
until then, this composite handles both shapes transparently.

KMS Decrypt is the dominant cost. A ``DEKCache`` between this provider
and KMS is mandatory in production: without it, every credential read
is a ~10-50ms KMS round trip plus per-request charges.
"""

from __future__ import annotations

import logging
from typing import Any

import boto3

from backend.app.security.dek_cache import DEKCache
from backend.app.security.encryption import EncryptionContext, KEKProvider, LocalKEKProvider

logger = logging.getLogger(__name__)

KMS_KEK_ID = "kms"


class KMSEnvelopeKEKProvider:
    """KEK provider backed by AWS KMS, with a local fallback for legacy rows."""

    def __init__(
        self,
        kms_key_arn: str,
        *,
        aws_access_key_id: str | None = None,
        aws_secret_access_key: str | None = None,
        cache: DEKCache | None = None,
        fallback_provider: KEKProvider | None = None,
    ) -> None:
        if not kms_key_arn or not kms_key_arn.strip():
            raise ValueError("kms_key_arn must be a non-empty string")
        self._kms_key_arn = kms_key_arn.strip()
        self._aws_region = self._extract_region_from_arn(self._kms_key_arn)
        self._aws_access_key_id = aws_access_key_id
        self._aws_secret_access_key = aws_secret_access_key
        self._client: Any | None = None
        self._cache = cache or DEKCache()
        # Legacy rows written before KMS was enabled carry kek_id="local"
        # and need LocalKEKProvider to unwrap. Defaults to a fresh
        # LocalKEKProvider derived from settings.encryption_key.
        self._fallback = fallback_provider or LocalKEKProvider()

    @staticmethod
    def _extract_region_from_arn(arn: str) -> str:
        parts = arn.split(":")
        if len(parts) < 4 or not parts[3]:
            raise ValueError(f"Invalid KMS ARN, cannot extract region: {arn!r}")
        return parts[3]

    @property
    def region(self) -> str:
        """Region extracted from the configured KMS ARN."""
        return self._aws_region

    def _kms_client(self) -> Any:
        if self._client is None:
            kwargs: dict[str, Any] = {"region_name": self._aws_region}
            if self._aws_access_key_id and self._aws_secret_access_key:
                kwargs["aws_access_key_id"] = self._aws_access_key_id
                kwargs["aws_secret_access_key"] = self._aws_secret_access_key
            self._client = boto3.client("kms", **kwargs)
        return self._client

    def wrap(self, dek: bytes, *, context: EncryptionContext) -> tuple[str, bytes]:
        """Encrypt the DEK with KMS and return the wrapped blob."""
        del context  # not used yet; reserved for tenant-scoped key selection
        resp = self._kms_client().encrypt(KeyId=self._kms_key_arn, Plaintext=dek)
        return KMS_KEK_ID, resp["CiphertextBlob"]

    def unwrap(self, kek_id: str, wrapped: bytes, *, context: EncryptionContext) -> bytes:
        """Decrypt the DEK, dispatching legacy rows to the fallback provider."""
        if kek_id != KMS_KEK_ID:
            return self._fallback.unwrap(kek_id, wrapped, context=context)

        cached = self._cache.get(wrapped)
        if cached is not None:
            return cached

        resp = self._kms_client().decrypt(CiphertextBlob=wrapped)
        dek = resp["Plaintext"]
        self._cache.put(wrapped, dek)
        return dek
