"""Adopt the premium schema into the OSS migration chain.

Creates the eight tables and the two ``users`` columns that previously lived in
the ``alembic_version_premium`` chain (p001..p030). Both chains already share a
single ``Base.metadata`` and are separated only by ``version_table`` plus an
``include_object`` filter, so the thirty file premium history is disposable and
only the resulting schema matters.

Hand-written rather than autogenerated. Autogenerate emits 157 operations, of
which only 21 belong to this merge; the rest is pre-existing drift between the
OSS models and the OSS chain (see #1513). It also gets the 21 wrong, because
the models carry Python-side ``default=`` rather than ``server_default=``, omit
``ix_admin_audit_logs_action_created``, and disagree with the deployed defaults
on the ``usage_quotas`` limits. This revision reproduces the deployed schema
instead: server defaults, ``ON DELETE`` actions, constraint names and physical
column order all match what p001..p030 actually built.

The eight tables have no OSS model yet. Their models still live in
clawbolt-premium and cannot be declared in both repos at once, since the shared
metadata would reject the duplicate. They move here with #1510.

On an existing premium deployment every object here already exists, so this
revision is stamped rather than run. Fresh databases run it for real.

Revision ID: 041
Revises: 040
Create Date: 2026-08-13
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "041"
down_revision: str | None = "040"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_NOW = sa.text("now()")


def upgrade() -> None:
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), server_default="user", nullable=False),
        sa.Column("plan", sa.String(length=20), server_default="free", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("email", sa.String(length=255), server_default="", nullable=False),
        sa.Column("llm_provider_override", sa.String(length=64), server_default="", nullable=False),
        sa.Column("llm_model_override", sa.String(length=128), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_subscriptions_user_id"),
    )
    op.create_index("ix_subscriptions_user_id", "subscriptions", ["user_id"], unique=True)

    op.create_table(
        "usage_quotas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("messages_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("messages_limit", sa.Integer(), server_default="50", nullable=False),
        sa.Column("tokens_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tokens_limit", sa.Integer(), server_default="100000", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_usage_quotas_user_id"),
        sa.UniqueConstraint("user_id", "period_start", name="uq_usage_quotas_user_period"),
    )
    op.create_index("ix_usage_quotas_user_id", "usage_quotas", ["user_id"])

    op.create_table(
        "deleted_user_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_user_id", sa.String(length=255), nullable=False),
        sa.Column("plan_at_deletion", sa.String(length=20), server_default="free", nullable=False),
        sa.Column("total_messages", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deleted_user_usage_original_user_id", "deleted_user_usage", ["original_user_id"]
    )

    op.create_table(
        "allowed_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_allowed_emails_email", "allowed_emails", ["email"], unique=True)

    op.create_table(
        "waitlist_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=50), server_default="homepage", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("name", sa.String(length=120), server_default="user", nullable=False),
        sa.Column("use_case", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_waitlist_entries_email", "waitlist_entries", ["email"], unique=True)

    op.create_table(
        "admin_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("label", sa.String(length=200), server_default="", nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_admin_api_keys_key_hash", "admin_api_keys", ["key_hash"], unique=True)
    op.create_index("ix_admin_api_keys_user_id", "admin_api_keys", ["user_id"])

    op.create_table(
        "admin_audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_user_id", sa.String(), nullable=True),
        sa.Column("target_user_id", sa.String(), nullable=True),
        sa.Column("endpoint", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("action", sa.String(length=64), nullable=True),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("admin_email", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["admin_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_admin_audit_logs_admin_user_id", "admin_audit_logs", ["admin_user_id"])
    op.create_index("ix_admin_audit_logs_target_user_id", "admin_audit_logs", ["target_user_id"])
    op.create_index("ix_admin_audit_logs_created_at", "admin_audit_logs", ["created_at"])
    # Declared in p022 but absent from the ORM model, so autogenerate drops it.
    op.create_index(
        "ix_admin_audit_logs_action_created", "admin_audit_logs", ["action", "created_at"]
    )

    op.create_table(
        "llm_payload_captures",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("current_era_payload", postgresql.JSONB(), nullable=False),
        sa.Column("current_era_min_message_seq", sa.BigInteger(), nullable=True),
        sa.Column("current_era_captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_era_request_id", sa.String(), nullable=True),
        sa.Column("current_era_payload_bytes", sa.Integer(), nullable=False),
        sa.Column("previous_era_payload", postgresql.JSONB(), nullable=True),
        sa.Column("previous_era_min_message_seq", sa.BigInteger(), nullable=True),
        sa.Column("previous_era_captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_era_request_id", sa.String(), nullable=True),
        sa.Column("previous_era_payload_bytes", sa.Integer(), nullable=True),
        sa.Column("current_era_response", postgresql.JSONB(), nullable=True),
        sa.Column("current_era_response_captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_era_response_bytes", sa.Integer(), nullable=True),
        sa.Column("previous_era_response", postgresql.JSONB(), nullable=True),
        sa.Column("previous_era_response_captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_era_response_bytes", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )

    # Premium columns on the OSS users table (p009). Naive DateTime, not tz-aware.
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("inactivity_warned_at", sa.DateTime(), nullable=True))
    op.create_index("ix_users_last_login_at", "users", ["last_login_at"])


def downgrade() -> None:
    op.drop_index("ix_users_last_login_at", table_name="users")
    op.drop_column("users", "inactivity_warned_at")
    op.drop_column("users", "last_login_at")
    for table in (
        "llm_payload_captures",
        "admin_audit_logs",
        "admin_api_keys",
        "waitlist_entries",
        "allowed_emails",
        "deleted_user_usage",
        "usage_quotas",
        "subscriptions",
    ):
        op.drop_table(table)
