from __future__ import annotations

from collections.abc import Awaitable, Callable
from dataclasses import dataclass, field
from enum import StrEnum
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel

if TYPE_CHECKING:
    from backend.app.agent.approval import ApprovalPolicy


class ToolTags(StrEnum):
    """Cross-cutting tool metadata tags."""

    SENDS_REPLY = "sends_reply"
    MODIFIES_PROFILE = "modifies_profile"


class ToolErrorKind(StrEnum):
    """Classification of tool errors to guide LLM self-correction."""

    VALIDATION = "validation"
    SERVICE = "service"
    NOT_FOUND = "not_found"
    PERMISSION = "permission"
    AUTH = "auth"
    INTERNAL = "internal"
    INTERRUPTED = "interrupted"


@dataclass
class ToolReceipt:
    """A deterministic, human-readable confirmation of a write-side action.

    Populated by tools that mutate external state (CompanyCam, QuickBooks,
    Calendar, etc.) so plain-text channels (iMessage, Telegram, SMS) can
    show the user what actually happened without relying on the LLM's
    claims. ``action`` is a hardcoded verb phrase; ``target`` is filled
    from real tool output; ``url`` is a deep link from the API response
    and is never generated by the LLM.
    """

    action: str
    target: str
    url: str | None = None


@dataclass
class ToolResult:
    """Structured result from a tool execution."""

    content: str
    is_error: bool = False
    error_kind: ToolErrorKind | None = None
    hint: str = ""
    receipt: ToolReceipt | None = None


ConcurrencyGroupResolver = Callable[[dict[str, Any]], str | None]


@dataclass
class Tool:
    """A tool that the agent can call."""

    name: str
    description: str
    function: Callable[..., Awaitable[ToolResult]]
    params_model: type[BaseModel]
    tags: set[ToolTags] = field(default_factory=set)
    usage_hint: str = ""
    approval_policy: ApprovalPolicy | None = None
    concurrency_group: str | ConcurrencyGroupResolver | None = None
    """Serialization key for parallel tool execution.

    The agent runs approved tool calls from a single model turn concurrently.
    Tools that share a non-None ``concurrency_group`` value run sequentially
    in submission order; tools with different keys (or ``None``) may run in
    parallel.

    Accepts either a static string or a callable that takes the tool's
    validated arguments and returns a key. Use the callable form when the
    same tool can target distinct shared resources by argument, for
    example a workspace ``write_file`` whose ``path`` decides which file
    is mutated. Use a string when the tool always touches the same
    resource (e.g. a single user-facing message stream).

    Set this for tools that mutate shared state another tool could touch in
    the same turn (a shared DB row, a workspace document, a disk file, the
    user-facing message stream). Read-only and stateless tools should leave
    it ``None``. Common keys in this codebase: ``"workspace_path:<path>"``
    for workspace document mutations (resolved per call), ``"user_outbound"``
    for reply senders, ``"user_integrations"`` for integration toggles.
    """


def _inline_refs(schema: dict[str, Any]) -> dict[str, Any]:
    """Inline $defs/$ref references so the schema is self-contained."""
    defs = schema.pop("$defs", {})
    if not defs:
        return schema

    def resolve(obj: Any) -> Any:
        if isinstance(obj, dict):
            if "$ref" in obj:
                ref_name = obj["$ref"].split("/")[-1]
                return resolve(defs.get(ref_name, obj))
            return {k: resolve(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [resolve(item) for item in obj]
        return obj

    return resolve(schema)


# JSON Schema containers whose *keys* are caller-chosen names rather than
# schema keywords. A parameter literally named ``title`` lives in one of these
# and must survive ``_strip_titles``; only annotation-level ``title`` keys are
# noise worth dropping. ``$defs`` / ``definitions`` are normally gone by the
# time we run (``_inline_refs`` pops them), and are listed for safety.
_NAME_KEYED_SCHEMA_CONTAINERS = frozenset(
    {"properties", "patternProperties", "$defs", "definitions"}
)


def _strip_titles(obj: Any, *, _in_name_map: bool = False) -> Any:
    """Recursively remove Pydantic's ``title`` annotations from a schema.

    Pydantic stamps a ``title`` onto every schema node, which is pure noise in
    the tool definitions we send on each request, so dropping it saves tokens.

    The subtlety is that ``title`` is only noise when it is a schema *keyword*.
    Inside ``properties`` the keys are parameter names, and a tool with a
    parameter named ``title`` (``calendar_create_event``) had that parameter
    deleted from the schema while ``required`` kept listing it. The model was
    then told ``title`` was mandatory and given no definition for it, so it had
    nowhere to put the value and the call could never validate. ``_in_name_map``
    tracks that context so parameter names are never filtered.
    """
    if isinstance(obj, dict):
        if _in_name_map:
            # Keys here are caller-chosen names, not schema keywords.
            return {k: _strip_titles(v) for k, v in obj.items()}
        return {
            k: _strip_titles(v, _in_name_map=k in _NAME_KEYED_SCHEMA_CONTAINERS)
            for k, v in obj.items()
            if k != "title"
        }
    if isinstance(obj, list):
        return [_strip_titles(item) for item in obj]
    return obj


def tool_to_function_schema(tool: Tool) -> dict[str, Any]:
    """Convert a Tool to the Anthropic Messages API tool schema.

    The JSON Schema is generated from the tool's ``params_model``
    (Pydantic BaseModel), which is the single source of truth for
    parameter definitions.
    """
    schema = tool.params_model.model_json_schema()
    schema = _inline_refs(schema)
    schema = _strip_titles(schema)

    return {
        "name": tool.name,
        "description": tool.description,
        "input_schema": schema,
    }
